"""TB_CHATTING 테이블에 JSON 필드 추가

Revision ID: 0106a8cbfafd
Revises: ed75368697f5
Create Date: 2025-02-06 11:43:15.362556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0106a8cbfafd'
down_revision: Union[str, None] = 'ed75368697f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_CHATTING', sa.Column('TRAVEL_DATA', mysql.JSON(), nullable=False, comment='여행 데이터(JSON 형식)'))
    op.add_column('TB_CHATTING', sa.Column('GPT_RESPONSE', mysql.JSON(), nullable=True, comment='GPT 응답(JSON 형식)'))
    op.alter_column('TB_CHATTING', 'CHAT_IDX',
               existing_type=mysql.INTEGER(),
               comment='채팅 식별자',
               existing_comment='채팅 고유번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TB_CHATTING', 'CROOM_IDX',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='채팅방 식별자',
               existing_comment='방 고유번호')
    op.alter_column('TB_CHATTING', 'USER_ID',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment='사용자 ID',
               existing_comment='발화자')
    op.alter_column('TB_CHATTING', 'CREATED_AT',
               existing_type=mysql.TIMESTAMP(),
               comment='생성 일시',
               existing_comment='발화 시간',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('TB_CHATTING', 'USER_CONTENT')
    op.drop_column('TB_CHATTING', 'CHAT_FILE')
    op.drop_column('TB_CHATTING', 'CHAT_CONTENT')
    op.drop_column('TB_CHATTING', 'CHAT_EMOTION')
    op.alter_column('TB_FESTIVAL', 'FEST_TEL',
               existing_type=mysql.VARCHAR(length=255),
               comment='행사 전화',
               existing_nullable=True)
    op.alter_column('TB_POI', 'POI_TEL',
               existing_type=mysql.VARCHAR(length=255),
               comment='여행지 전화번호',
               existing_nullable=True)
    op.alter_column('TB_POI', 'LAT',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='위도',
               existing_nullable=True)
    op.alter_column('TB_POI', 'LON',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='경도',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TB_POI', 'LON',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='경도',
               existing_nullable=True)
    op.alter_column('TB_POI', 'LAT',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='위도',
               existing_nullable=True)
    op.alter_column('TB_POI', 'POI_TEL',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='여행지 전화번호',
               existing_nullable=True)
    op.alter_column('TB_FESTIVAL', 'FEST_TEL',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='행사 전화',
               existing_nullable=True)
    op.add_column('TB_CHATTING', sa.Column('CHAT_EMOTION', mysql.VARCHAR(length=1000), nullable=True, comment='발화 이모티콘'))
    op.add_column('TB_CHATTING', sa.Column('CHAT_CONTENT', mysql.TEXT(), nullable=True, comment='발화 내용'))
    op.add_column('TB_CHATTING', sa.Column('CHAT_FILE', mysql.VARCHAR(length=1000), nullable=True, comment='발화 첨부파일'))
    op.add_column('TB_CHATTING', sa.Column('USER_CONTENT', mysql.TEXT(), nullable=True))
    op.alter_column('TB_CHATTING', 'CREATED_AT',
               existing_type=mysql.TIMESTAMP(),
               comment='발화 시간',
               existing_comment='생성 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('TB_CHATTING', 'USER_ID',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment='발화자',
               existing_comment='사용자 ID')
    op.alter_column('TB_CHATTING', 'CROOM_IDX',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='방 고유번호',
               existing_comment='채팅방 식별자')
    op.alter_column('TB_CHATTING', 'CHAT_IDX',
               existing_type=mysql.INTEGER(),
               comment='채팅 고유번호',
               existing_comment='채팅 식별자',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('TB_CHATTING', 'GPT_RESPONSE')
    op.drop_column('TB_CHATTING', 'TRAVEL_DATA')
    # ### end Alembic commands ###
