"""TB_CROOM 테이블에 GPT_RESPONSE 컬럼 추가

Revision ID: 2202e4417648
Revises: 0106a8cbfafd
Create Date: 2025-02-06 18:03:55.999154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2202e4417648'
down_revision: Union[str, None] = '0106a8cbfafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_CROOM', sa.Column('GPT_RESPONSE', sa.Text(), nullable=True))
    op.alter_column('TB_CROOM', 'CROOM_IDX',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='방 고유번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TB_CROOM', 'CROOM_TITLE',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               nullable=False,
               comment=None,
               existing_comment='방 제목')
    op.alter_column('TB_CROOM', 'CROOM_INFO',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='방 소개',
               existing_nullable=True)
    op.alter_column('TB_CROOM', 'USER_ID',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='방 개설자')
    op.alter_column('TB_CROOM', 'CROOM_LIMIT',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='방 인원수',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('TB_CROOM', 'CROOM_STATUS',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False,
               comment=None,
               existing_comment='방 상태')
    op.alter_column('TB_CROOM', 'CREATED_AT',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='방 개설일자',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TB_CROOM', 'CREATED_AT',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='방 개설일자',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('TB_CROOM', 'CROOM_STATUS',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=True,
               comment='방 상태')
    op.alter_column('TB_CROOM', 'CROOM_LIMIT',
               existing_type=mysql.INTEGER(),
               comment='방 인원수',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('TB_CROOM', 'USER_ID',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment='방 개설자')
    op.alter_column('TB_CROOM', 'CROOM_INFO',
               existing_type=mysql.TEXT(),
               comment='방 소개',
               existing_nullable=True)
    op.alter_column('TB_CROOM', 'CROOM_TITLE',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               nullable=True,
               comment='방 제목')
    op.alter_column('TB_CROOM', 'CROOM_IDX',
               existing_type=mysql.INTEGER(),
               comment='방 고유번호',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('TB_CROOM', 'GPT_RESPONSE')
    # ### end Alembic commands ###
